/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminNotification {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'targetEmployeeId' : [] | [string],
  'message' : string,
  'readBy' : Array<string>,
  'companyId' : string,
}
export interface AssignRoleInput { 'userId' : Principal, 'roleId' : bigint }
export interface Attendance {
  'id' : bigint,
  'totalHours' : number,
  'orgId' : bigint,
  'date' : string,
  'punchOut' : [] | [string],
  'createdAt' : bigint,
  'attendanceType' : AttendanceType,
  'employeeId' : bigint,
  'punchIn' : [] | [string],
  'notes' : string,
}
export type AttendanceType = { 'halfDay' : null } |
  { 'present' : null } |
  { 'leave' : null } |
  { 'absent' : null };
export type AttributeType = { 'list' : null } |
  { 'text' : null } |
  { 'number' : null };
export interface BillOfMaterial {
  'id' : BomId,
  'status' : string,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'components' : Array<BomComponent>,
  'productName' : string,
  'enabled' : boolean,
  'revision' : string,
}
export type BillStatus = { 'partially_paid' : null } |
  { 'paid' : null } |
  { 'approved' : null } |
  { 'overdue' : null } |
  { 'draft' : null };
export interface BillTo {
  'taxId' : [] | [string],
  'name' : string,
  'dealId' : [] | [bigint],
  'email' : string,
  'address' : [] | [string],
  'contactId' : [] | [bigint],
}
export interface BillingEntry {
  'id' : bigint,
  'orgId' : OrgId,
  'description' : string,
  'stripeInvoiceId' : [] | [string],
  'currency' : string,
  'amount' : bigint,
  'paidAt' : Timestamp,
}
export interface BomComponent {
  'itemId' : bigint,
  'cost' : number,
  'unit' : string,
  'quantity' : number,
}
export type BomId = bigint;
export interface BulkImportError { 'message' : string, 'index' : bigint }
export interface BulkImportResult {
  'errors' : Array<BulkImportError>,
  'successCount' : bigint,
}
export interface CashFlowForecast {
  'projectedBalance' : bigint,
  'date' : Timestamp,
}
export interface Category {
  'id' : CategoryId,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'description' : string,
}
export interface CategoryExpense {
  'category' : TransactionCategory,
  'amount' : bigint,
}
export type CategoryId = bigint;
export interface Contact {
  'id' : ContactId,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'email' : [] | [string],
  'updatedAt' : Timestamp,
  'company' : [] | [string],
  'phone' : [] | [string],
}
export type ContactId = bigint;
export interface ContactInput {
  'name' : string,
  'tags' : Array<string>,
  'email' : [] | [string],
  'company' : [] | [string],
  'phone' : [] | [string],
}
export type ContactSortField = { 'name' : null } |
  { 'createdAt' : null } |
  { 'company' : null };
export interface CostOfProduction {
  'id' : CostOfProductionId,
  'orgId' : OrgId,
  'period' : string,
  'moId' : ManufacturingOrderId,
  'createdAt' : Timestamp,
  'totalCost' : number,
  'enabled' : boolean,
  'labourCost' : number,
  'notes' : string,
  'scrapCost' : number,
  'materialCost' : number,
  'overheadCost' : number,
}
export type CostOfProductionId = bigint;
export type CourierProvider = { 'bluedart' : null } |
  { 'manual' : null } |
  { 'delhivery' : null } |
  { 'fedex' : null };
export interface CreateAttendanceInput {
  'totalHours' : number,
  'date' : string,
  'punchOut' : [] | [string],
  'attendanceType' : AttendanceType,
  'employeeId' : bigint,
  'punchIn' : [] | [string],
  'notes' : string,
}
export interface CreateBomInput {
  'status' : string,
  'components' : Array<BomComponent>,
  'productName' : string,
  'revision' : string,
}
export interface CreateCategoryInput {
  'orgId' : OrgId,
  'name' : string,
  'description' : string,
}
export interface CreateCostOfProductionInput {
  'period' : string,
  'moId' : ManufacturingOrderId,
  'labourCost' : number,
  'notes' : string,
  'scrapCost' : number,
  'materialCost' : number,
  'overheadCost' : number,
}
export interface CreateCreditNoteInput {
  'customer' : string,
  'invoiceId' : bigint,
  'amount' : number,
  'reason' : string,
}
export interface CreateCreditNoteInput__1 {
  'supplier' : string,
  'amount' : number,
  'billId' : bigint,
  'reason' : string,
}
export interface CreateDebitNoteInput {
  'customer' : string,
  'invoiceId' : bigint,
  'amount' : number,
  'reason' : string,
}
export interface CreateDebitNoteInput__1 {
  'supplier' : string,
  'amount' : number,
  'billId' : bigint,
  'reason' : string,
}
export interface CreateEmployeeInput {
  'employeeCode' : string,
  'name' : string,
  'designation' : string,
  'joiningDate' : string,
  'email' : string,
  'salaryGrade' : string,
  'phone' : string,
  'department' : string,
}
export interface CreateEmployeeInput__1 {
  'password' : string,
  'name' : string,
  'designation' : string,
  'email' : string,
  'modulePermissions' : Array<[string, boolean]>,
  'department' : string,
  'companyId' : string,
}
export interface CreateFinanceCategoryInput {
  'categoryType' : FinanceCategoryType,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'parentId' : [] | [string],
}
export interface CreateFinishedGoodInput {
  'status' : string,
  'expiryDate' : [] | [Timestamp],
  'moId' : ManufacturingOrderId,
  'productId' : bigint,
  'productionDate' : Timestamp,
  'warehouseLocation' : string,
  'quantity' : number,
  'batchNo' : string,
}
export interface CreateGroupInput {
  'parentGroup' : [] | [bigint],
  'description' : string,
  'groupName' : string,
}
export interface CreateHsnSacCodeInput {
  'name' : string,
  'description' : string,
  'hsnCode' : [] | [string],
  'isActive' : boolean,
  'codeType' : HsnSacCodeType,
  'sacCode' : [] | [string],
  'category' : string,
}
export interface CreateIncentiveSchemeInput {
  'rewardValue' : number,
  'effectiveTo' : [] | [Timestamp],
  'schemeName' : string,
  'rewardType' : RewardType,
  'category' : string,
  'targetValue' : number,
  'targetMetric' : TargetMetric,
  'effectiveFrom' : Timestamp,
}
export interface CreateInventoryCategoryInput {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'parentId' : [] | [bigint],
}
export interface CreateInvoiceInput {
  'lineItems' : Array<LineItem__2>,
  'taxPercent' : number,
  'dueDate' : Timestamp,
  'currency' : string,
  'notes' : [] | [string],
  'billTo' : BillTo,
}
export interface CreateItemAttributeInput {
  'name' : string,
  'type' : AttributeType,
  'values' : Array<string>,
}
export interface CreateItemMasterInput {
  'categoryId' : [] | [bigint],
  'enableSerial' : boolean,
  'categoryName' : string,
  'partNumber' : string,
  'name' : string,
  'rate' : number,
  'uomName' : string,
  'description' : string,
  'hsnCode' : string,
  'enableShelfLife' : boolean,
  'enableBatch' : boolean,
  'taxPct' : number,
  'attributes' : Array<ItemAttribute_>,
  'barcode' : string,
  'itemCode' : string,
  'uomId' : [] | [bigint],
}
export interface CreateLocationInput {
  'email' : string,
  'state' : string,
  'locationCode' : string,
  'locationName' : string,
}
export interface CreateMachineInput {
  'status' : MachineStatus,
  'code' : string,
  'lastMaintenance' : [] | [Timestamp],
  'name' : string,
  'capacityUnit' : string,
  'capacity' : number,
  'location' : string,
  'machineType' : string,
}
export interface CreateManufacturingOrderInput {
  'dueDate' : Timestamp,
  'workOrderId' : WorkOrderId,
  'quantity' : number,
  'startDate' : Timestamp,
}
export interface CreateNotificationInput {
  'title' : string,
  'targetEmployeeId' : [] | [string],
  'message' : string,
  'companyId' : string,
}
export interface CreatePayrollInput { 'month' : bigint, 'year' : bigint }
export interface CreatePosTransactionInput {
  'customerName' : [] | [string],
  'paymentMode' : PaymentMode__1,
  'customerId' : [] | [bigint],
  'items' : Array<PosItem>,
}
export interface CreateProductInput {
  'categoryId' : [] | [CategoryId],
  'taxPercent' : bigint,
  'stockQty' : bigint,
  'partNumber' : string,
  'orgId' : OrgId,
  'name' : string,
  'rate' : number,
  'unit' : string,
  'description' : string,
  'hsnCode' : string,
}
export interface CreateProductionPlanInput {
  'status' : string,
  'period' : string,
  'targetQty' : number,
  'workOrderIds' : Array<WorkOrderId>,
}
export interface CreatePurchaseBillInput {
  'lineItems' : Array<LineItem>,
  'supplierName' : string,
  'poId' : [] | [bigint],
  'dueDate' : Timestamp,
  'amountPaid' : number,
  'notes' : string,
  'supplierId' : bigint,
}
export interface CreatePurchaseOrderInput {
  'lineItems' : Array<LineItem>,
  'supplierName' : string,
  'notes' : string,
  'supplierId' : bigint,
}
export interface CreatePurchaseReturnInput {
  'supplier' : string,
  'items' : Array<ReturnItem>,
  'billId' : bigint,
  'reason' : string,
}
export interface CreateQualityControlInput {
  'result' : QcResult,
  'inspectionDate' : Timestamp,
  'failQty' : number,
  'moId' : ManufacturingOrderId,
  'passQty' : number,
  'defects' : Array<string>,
  'notes' : string,
  'inspector' : string,
}
export interface CreateQuotationInput {
  'customerName' : string,
  'lineItems' : Array<LineItem>,
  'notes' : string,
  'customerId' : bigint,
  'validUntil' : Timestamp,
}
export interface CreateReceiptInput {
  'receiptDate' : Timestamp,
  'reference' : string,
  'invoiceId' : [] | [bigint],
  'paymentMode' : PaymentMode__1,
  'customerId' : bigint,
  'amount' : number,
  'isAdvance' : boolean,
}
export interface CreateRefundRequestInput {
  'orgId' : OrgId,
  'period' : string,
  'refundType' : string,
  'amount' : number,
  'reason' : string,
}
export interface CreateRequisitionInput {
  'moId' : ManufacturingOrderId,
  'items' : Array<RequisitionItem>,
  'requestedBy' : string,
}
export interface CreateRoleInput {
  'roleName' : string,
  'screens' : Array<string>,
  'description' : string,
}
export interface CreateRoutingOperationInput {
  'costPerHour' : number,
  'code' : string,
  'name' : string,
  'description' : string,
  'machineId' : MachineId,
  'standardTime' : number,
  'sequence' : bigint,
}
export interface CreateSaleReturnInput {
  'customer' : string,
  'invoiceId' : bigint,
  'items' : Array<ReturnItem>,
  'reason' : string,
}
export interface CreateSalesOrderInput {
  'customerName' : string,
  'lineItems' : Array<LineItem>,
  'notes' : string,
  'customerId' : bigint,
}
export interface CreateScrapRecordInput {
  'scrapReason' : string,
  'date' : Timestamp,
  'moId' : ManufacturingOrderId,
  'recordedBy' : string,
  'scrapQty' : number,
  'scrapValue' : number,
  'machineId' : MachineId,
}
export interface CreateShipmentInput {
  'weight' : [] | [number],
  'consigneePhone' : string,
  'consigneeAddress' : string,
  'trackingNo' : [] | [string],
  'consigneeName' : string,
  'orderId' : [] | [bigint],
  'transporterPhone' : [] | [string],
  'courierProvider' : CourierProvider,
  'dimensions' : [] | [string],
  'docId' : [] | [bigint],
  'transporterName' : [] | [string],
}
export interface CreateShopFloorInput {
  'startTime' : Timestamp,
  'workOrderId' : WorkOrderId,
  'operatorName' : string,
  'operationId' : RoutingOperationId,
  'notes' : string,
  'quantity' : number,
  'machineId' : MachineId,
}
export interface CreateSlipInput {
  'da' : number,
  'hra' : number,
  'month' : bigint,
  'otherAllowances' : number,
  'year' : bigint,
  'tdsDeduction' : number,
  'employeeId' : bigint,
  'esiDeduction' : number,
  'advanceDeduction' : number,
  'basicSalary' : number,
  'pfDeduction' : number,
}
export interface CreateSupplierPaymentInput {
  'reference' : string,
  'paymentDate' : Timestamp,
  'paymentMode' : PaymentMode,
  'amount' : number,
  'supplierId' : bigint,
  'billId' : [] | [bigint],
  'isAdvance' : boolean,
}
export interface CreateTaskInput {
  'title' : string,
  'assignedTo' : string,
  'createdBy' : string,
  'dueDate' : bigint,
  'description' : string,
  'priority' : TaskPriority,
  'fileUrl' : [] | [string],
  'companyId' : string,
}
export interface CreateUomInput {
  'baseUnit' : string,
  'name' : string,
  'conversionFactor' : number,
  'symbol' : string,
}
export interface CreateWorkOrderInput {
  'plannedEnd' : Timestamp,
  'notes' : string,
  'quantity' : number,
  'plannedStart' : Timestamp,
  'bomId' : BomId,
}
export interface CsvLeadRow {
  'source' : string,
  'name' : string,
  'email' : [] | [string],
  'company' : [] | [string],
  'notes' : string,
  'phone' : [] | [string],
}
export interface CustomerReceipt {
  'id' : bigint,
  'receiptDate' : Timestamp,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'reference' : string,
  'invoiceId' : [] | [bigint],
  'paymentMode' : PaymentMode__1,
  'customerId' : bigint,
  'amount' : number,
  'isAdvance' : boolean,
}
export interface DashboardLayout {
  'updatedAt' : bigint,
  'adminEmail' : string,
  'widgetConfig' : string,
}
export interface Deal {
  'id' : DealId,
  'closeDate' : [] | [Timestamp],
  'value' : bigint,
  'orgId' : OrgId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'updatedAt' : Timestamp,
  'stage' : DealStage,
  'contactId' : [] | [ContactId],
}
export type DealId = bigint;
export interface DealInput {
  'closeDate' : [] | [Timestamp],
  'value' : bigint,
  'owner' : Principal,
  'name' : string,
  'stage' : DealStage,
  'contactId' : [] | [ContactId],
}
export interface DealNote {
  'id' : NoteId,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'text' : string,
  'dealId' : DealId,
}
export interface DealNoteInput { 'text' : string, 'dealId' : DealId }
export type DealStage = { 'closedWon' : null } |
  { 'prospect' : null } |
  { 'negotiation' : null } |
  { 'qualified' : null } |
  { 'closedLost' : null };
export interface DealStageEvent {
  'changedAt' : Timestamp,
  'changedBy' : Principal,
  'orgId' : OrgId,
  'fromStage' : [] | [DealStage],
  'toStage' : DealStage,
  'dealId' : DealId,
}
export interface Employee {
  'id' : bigint,
  'status' : EmployeeStatus,
  'employeeCode' : string,
  'orgId' : bigint,
  'name' : string,
  'designation' : string,
  'createdAt' : bigint,
  'joiningDate' : string,
  'email' : string,
  'salaryGrade' : string,
  'enabled' : boolean,
  'phone' : string,
  'department' : string,
}
export type EmployeeStatus = { 'active' : null } |
  { 'inactive' : null };
export interface ExtendedLead {
  'id' : LeadId,
  'status' : LeadStatus,
  'source' : LeadSource,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'score' : bigint,
  'updatedAt' : Timestamp,
  'notes' : string,
  'contactId' : ContactId,
}
export interface ExtendedLeadInput {
  'status' : LeadStatus,
  'source' : LeadSource,
  'notes' : string,
  'contactId' : ContactId,
}
export interface FilingPeriod { 'month' : bigint, 'year' : bigint }
export type FilingStatus = { 'submitted' : null } |
  { 'acknowledged' : null } |
  { 'draft' : null };
export interface FinanceCategory {
  'id' : string,
  'categoryType' : FinanceCategoryType,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'parentId' : [] | [string],
}
export interface FinanceCategoryFilter {
  'categoryType' : [] | [FinanceCategoryType],
  'isActive' : [] | [boolean],
  'parentId' : [] | [string],
}
export type FinanceCategoryType = { 'expense' : null } |
  { 'income' : null };
export interface FinanceDashboard {
  'mrr' : bigint,
  'budgetRemaining' : bigint,
  'budgetUtilizationPct' : bigint,
  'expensesByCategory' : Array<CategoryExpense>,
  'revenueMTD' : bigint,
  'revenueGrowthPct' : bigint,
  'budgetSpent' : bigint,
  'budgetAllocated' : bigint,
  'monthlyRevenueTrend' : Array<MonthlyRevenue>,
}
export interface FinishedGood {
  'id' : FinishedGoodId,
  'status' : string,
  'orgId' : OrgId,
  'expiryDate' : [] | [Timestamp],
  'moId' : ManufacturingOrderId,
  'createdAt' : Timestamp,
  'productId' : bigint,
  'productionDate' : Timestamp,
  'enabled' : boolean,
  'warehouseLocation' : string,
  'quantity' : number,
  'batchNo' : string,
}
export type FinishedGoodId = bigint;
export type GroupStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface Group_ {
  'id' : bigint,
  'status' : GroupStatus,
  'parentGroup' : [] | [bigint],
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'description' : string,
  'groupName' : string,
}
export interface GstRefundRequest {
  'id' : bigint,
  'status' : string,
  'acknowledgedAt' : [] | [bigint],
  'orgId' : OrgId,
  'period' : string,
  'createdAt' : bigint,
  'refundType' : string,
  'amount' : number,
  'reason' : string,
  'filedAt' : [] | [bigint],
}
export interface GstReturn {
  'id' : GstReturnId,
  'status' : FilingStatus,
  'orgId' : OrgId,
  'period' : FilingPeriod,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'gstr1Entries' : Array<Gstr1Entry>,
  'gstr3bEntry' : Gstr3bEntry,
  'returnType' : GstReturnType,
  'filedAt' : [] | [Timestamp],
}
export type GstReturnId = bigint;
export type GstReturnType = { 'gstr1' : null } |
  { 'gstr3b' : null };
export interface Gstr1Entry {
  'customerGstin' : [] | [string],
  'cgst' : number,
  'igst' : number,
  'taxableValue' : number,
  'sgst' : number,
  'hsnCode' : string,
  'invoiceDate' : Timestamp,
  'invoiceNumber' : string,
}
export interface Gstr3bEntry {
  'netTax' : number,
  'cgstPayable' : number,
  'igstPayable' : number,
  'sgstPayable' : number,
  'inputTaxCredit' : number,
}
export interface HsnSacCode {
  'id' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'hsnCode' : [] | [string],
  'isActive' : boolean,
  'codeType' : HsnSacCodeType,
  'updatedAt' : Timestamp,
  'sacCode' : [] | [string],
  'category' : string,
}
export type HsnSacCodeType = { 'auto' : null } |
  { 'manual' : null };
export interface HsnSacFilter {
  'isActive' : [] | [boolean],
  'codeType' : [] | [HsnSacCodeType],
  'category' : [] | [string],
}
export interface ImportResult { 'errors' : Array<RowError>, 'success' : bigint }
export interface IncentiveScheme {
  'id' : bigint,
  'status' : SchemeStatus,
  'orgId' : OrgId,
  'rewardValue' : number,
  'createdAt' : Timestamp,
  'effectiveTo' : [] | [Timestamp],
  'schemeName' : string,
  'rewardType' : RewardType,
  'category' : string,
  'targetValue' : number,
  'targetMetric' : TargetMetric,
  'effectiveFrom' : Timestamp,
}
export type InteractionKind = { 'other' : null } |
  { 'call' : null } |
  { 'email' : null } |
  { 'meeting' : null };
export interface InteractionNote {
  'id' : NoteId,
  'orgId' : OrgId,
  'kind' : InteractionKind,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'occurredAt' : Timestamp,
  'contactId' : ContactId,
  'outcome' : string,
}
export interface InteractionNoteInput {
  'kind' : InteractionKind,
  'occurredAt' : Timestamp,
  'contactId' : ContactId,
  'outcome' : string,
}
export interface InventoryCategory {
  'id' : bigint,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'parentId' : [] | [bigint],
}
export type InvoiceId = bigint;
export type InvoiceStatus = { 'paid' : null } |
  { 'sent' : null } |
  { 'voided' : null } |
  { 'overdue' : null } |
  { 'draft' : null };
export interface InvoiceView {
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'lineItems' : Array<LineItem__2>,
  'orgInfo' : OrgBillingInfo,
  'taxPercent' : number,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'dueDate' : Timestamp,
  'sentAt' : [] | [Timestamp],
  'invoiceNumber' : string,
  'currency' : string,
  'notes' : [] | [string],
  'stripePaymentIntentId' : [] | [string],
  'stripeSessionId' : [] | [string],
  'stripePaymentLinkId' : [] | [string],
  'paidAt' : [] | [Timestamp],
  'billTo' : BillTo,
}
export interface ItemAttributeDef {
  'id' : bigint,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'type' : AttributeType,
  'values' : Array<string>,
}
export interface ItemAttribute_ {
  'value' : string,
  'name' : string,
  'attributeId' : string,
}
export interface ItemMaster {
  'id' : bigint,
  'categoryId' : [] | [bigint],
  'enableSerial' : boolean,
  'categoryName' : string,
  'partNumber' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'rate' : number,
  'uomName' : string,
  'description' : string,
  'hsnCode' : string,
  'enableShelfLife' : boolean,
  'enableBatch' : boolean,
  'taxPct' : number,
  'attributes' : Array<ItemAttribute_>,
  'barcode' : string,
  'itemCode' : string,
  'uomId' : [] | [bigint],
}
export interface Lead {
  'id' : LeadId,
  'status' : LeadStatus,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'score' : bigint,
  'updatedAt' : Timestamp,
  'contactId' : ContactId,
}
export type LeadId = bigint;
export interface LeadInput { 'status' : LeadStatus, 'contactId' : ContactId }
export type LeadSource = { 'csv' : null } |
  { 'globallinker' : null } |
  { 'tradeindia' : null } |
  { 'metaAds' : null } |
  { 'websiteWebhook' : null } |
  { 'google' : null } |
  { 'indiamart' : null } |
  { 'exportindia' : null } |
  { 'manual' : null } |
  { 'justdial' : null } |
  { 'facebookPage' : null };
export type LeadStatus = { 'new' : null } |
  { 'lost' : null } |
  { 'converted' : null } |
  { 'qualified' : null };
export interface LedgerEntry {
  'transaction' : Transaction,
  'runningBalance' : bigint,
}
export interface LineItem {
  'qty' : number,
  'total' : number,
  'rate' : number,
  'description' : string,
  'taxPct' : number,
}
export interface LineItem__2 {
  'rateInCents' : bigint,
  'description' : string,
  'quantity' : number,
}
export interface Location {
  'id' : bigint,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'email' : string,
  'state' : string,
  'locationCode' : string,
  'locationName' : string,
}
export interface Machine {
  'id' : MachineId,
  'status' : MachineStatus,
  'orgId' : OrgId,
  'code' : string,
  'lastMaintenance' : [] | [Timestamp],
  'name' : string,
  'createdAt' : Timestamp,
  'enabled' : boolean,
  'capacityUnit' : string,
  'capacity' : number,
  'location' : string,
  'machineType' : string,
}
export type MachineId = bigint;
export type MachineStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'maintenance' : null };
export interface ManufacturingOrder {
  'id' : ManufacturingOrderId,
  'status' : MoStatus,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'workOrderId' : WorkOrderId,
  'enabled' : boolean,
  'quantity' : number,
  'completedQty' : number,
  'startDate' : Timestamp,
}
export type ManufacturingOrderId = bigint;
export type MoStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'released' : null } |
  { 'draft' : null } |
  { 'inProgress' : null };
export interface MonthlyRevenue {
  'month' : bigint,
  'revenue' : bigint,
  'expenses' : bigint,
  'year' : bigint,
}
export interface MonthlySummary {
  'net' : bigint,
  'month' : bigint,
  'expenses' : bigint,
  'year' : bigint,
  'income' : bigint,
}
export type NoteId = bigint;
export type NoteStatus = { 'cancelled' : null } |
  { 'applied' : null } |
  { 'approved' : null } |
  { 'draft' : null };
export type NotifType = { 'Invoice' : null } |
  { 'System' : null } |
  { 'GSTFiling' : null } |
  { 'B2BSyncNotif' : null };
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'orgId' : OrgId__15,
  'notifType' : NotifType,
  'userId' : Principal,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
}
export type NotificationId = string;
export interface Org {
  'id' : OrgId,
  'pan' : [] | [string],
  'timezone' : string,
  'orgType' : OrgType,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'slug' : string,
  'contactPerson' : [] | [OrgContactPerson],
  'gstin' : [] | [string],
  'address' : [] | [OrgAddress],
}
export interface OrgAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
  'postal' : string,
}
export interface OrgBillingInfo {
  'taxId' : [] | [string],
  'name' : string,
  'logoUrl' : [] | [string],
  'address' : string,
}
export interface OrgConfiguration {
  'id' : bigint,
  'orgId' : OrgId,
  'enableSerialization' : boolean,
  'trackInventory' : boolean,
  'enableBatches' : boolean,
  'invoiceTemplate' : string,
  'enableShelfLife' : boolean,
  'updatedAt' : Timestamp,
  'logoUrl' : string,
  'dateFormat' : string,
  'paymentGatewayKey' : string,
  'paymentGatewayType' : string,
  'enableBarcoding' : boolean,
  'currency' : string,
  'numberSeriesInvoice' : string,
  'taxAdjustment' : number,
  'numberSeriesPO' : string,
  'numberSeriesSO' : string,
}
export interface OrgContactPerson {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type OrgId = bigint;
export type OrgId__15 = string;
export interface OrgMember {
  'principal' : Principal,
  'joinedAt' : Timestamp,
  'role' : OrgRole,
  'invitedBy' : [] | [Principal],
}
export type OrgRole = { 'member' : null } |
  { 'admin' : null } |
  { 'owner' : null };
export interface OrgSubscription {
  'status' : SubscriptionStatus,
  'orgId' : OrgId,
  'currentPeriodStart' : [] | [Timestamp],
  'stripeSubscriptionId' : [] | [string],
  'plan' : PlanTier,
  'currentPeriodEnd' : [] | [Timestamp],
  'trialEnd' : [] | [Timestamp],
  'stripeCustomerId' : [] | [string],
  'cancelAtPeriodEnd' : boolean,
}
export interface OrgSummary {
  'id' : OrgId,
  'timezone' : string,
  'name' : string,
  'slug' : string,
  'myRole' : OrgRole,
}
export type OrgType = { 'company' : null } |
  { 'individual' : null };
export type PaymentMode = { 'upi' : null } |
  { 'bank' : null } |
  { 'cash' : null } |
  { 'cheque' : null };
export type PaymentMode__1 = { 'upi' : null } |
  { 'bank' : null } |
  { 'card' : null } |
  { 'cash' : null } |
  { 'cheque' : null } |
  { 'online' : null };
export interface Payroll {
  'id' : bigint,
  'totalEmployees' : bigint,
  'status' : PayrollStatus,
  'month' : bigint,
  'totalDeductions' : number,
  'orgId' : bigint,
  'totalNetPay' : number,
  'createdAt' : bigint,
  'year' : bigint,
  'processedAt' : bigint,
  'totalGrossPay' : number,
}
export type PayrollStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'processed' : null };
export interface PendingInvite {
  'id' : bigint,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'role' : OrgRole,
  'invitedBy' : Principal,
  'email' : string,
}
export interface Permission {
  'id' : bigint,
  'roleName' : string,
  'orgId' : OrgId,
  'screen' : string,
  'createdAt' : Timestamp,
  'canEdit' : boolean,
  'canView' : boolean,
  'canDelete' : boolean,
  'module' : string,
  'roleId' : bigint,
  'canCreate' : boolean,
}
export interface PfEsiConfig {
  'id' : bigint,
  'insurancePremiumPerEmployee' : number,
  'esiRate' : number,
  'orgId' : bigint,
  'createdAt' : bigint,
  'pfEmployerRate' : number,
  'pfEmployeeRate' : number,
  'effectiveFrom' : string,
}
export interface PipelineSummary {
  'stages' : Array<StageSummary>,
  'averageDealSize' : bigint,
  'winRate' : bigint,
}
export type PlanTier = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'free' : null };
export type PoStatus = { 'sent' : null } |
  { 'approved' : null } |
  { 'draft' : null } |
  { 'billed' : null };
export interface PortalAdminSession {
  'role' : PortalRole,
  'email' : string,
  'adminName' : string,
  'logoUrl' : [] | [string],
  'companyId' : string,
}
export interface PortalApiKeyInfo {
  'maskedKey' : string,
  'lastSynced' : [] | [Timestamp],
  'syncStatus' : SyncStatus,
  'portal' : PortalType,
}
export interface PortalEmployee {
  'name' : string,
  'designation' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'email' : string,
  'employeeId' : string,
  'modulePermissions' : Array<[string, boolean]>,
  'passwordHash' : string,
  'department' : string,
  'companyId' : string,
}
export interface PortalEmployeeSession {
  'name' : string,
  'role' : PortalRole,
  'employeeId' : string,
  'companyId' : string,
}
export type PortalRole = { 'portalAdmin' : null } |
  { 'portalEmployee' : null };
export interface PortalTask {
  'id' : string,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'dueDate' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'priority' : TaskPriority,
  'fileUrl' : [] | [string],
  'companyId' : string,
}
export type PortalType = { 'globallinker' : null } |
  { 'tradeindia' : null } |
  { 'metaAds' : null } |
  { 'websiteWebhook' : null } |
  { 'google' : null } |
  { 'indiamart' : null } |
  { 'exportindia' : null } |
  { 'justdial' : null } |
  { 'facebookPage' : null };
export interface PosItem {
  'qty' : number,
  'total' : number,
  'name' : string,
  'rate' : number,
  'productId' : string,
  'taxPct' : number,
}
export interface PosTransaction {
  'id' : bigint,
  'customerName' : [] | [string],
  'total' : number,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'taxTotal' : number,
  'paymentMode' : PaymentMode__1,
  'customerId' : [] | [bigint],
  'items' : Array<PosItem>,
  'subtotal' : number,
}
export interface Product {
  'id' : ProductId,
  'categoryId' : [] | [CategoryId],
  'taxPercent' : bigint,
  'stockQty' : bigint,
  'partNumber' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'rate' : number,
  'unit' : string,
  'description' : string,
  'hsnCode' : string,
}
export type ProductId = bigint;
export interface ProductionPlan {
  'id' : ProductionPlanId,
  'status' : string,
  'orgId' : OrgId,
  'period' : string,
  'createdAt' : Timestamp,
  'targetQty' : number,
  'enabled' : boolean,
  'actualQty' : number,
  'workOrderIds' : Array<WorkOrderId>,
}
export type ProductionPlanId = bigint;
export interface PurchaseBill {
  'id' : bigint,
  'status' : BillStatus,
  'lineItems' : Array<LineItem>,
  'total' : number,
  'orgId' : OrgId,
  'supplierName' : string,
  'createdAt' : Timestamp,
  'poId' : [] | [bigint],
  'taxTotal' : number,
  'dueDate' : Timestamp,
  'amountPaid' : number,
  'notes' : string,
  'billNumber' : string,
  'supplierId' : bigint,
  'subtotal' : number,
}
export interface PurchaseCreditNote {
  'id' : bigint,
  'status' : NoteStatus,
  'orgId' : OrgId,
  'creditNumber' : string,
  'supplier' : string,
  'createdAt' : Timestamp,
  'amount' : number,
  'billId' : bigint,
  'reason' : string,
}
export interface PurchaseDebitNote {
  'id' : bigint,
  'status' : NoteStatus,
  'debitNumber' : string,
  'orgId' : OrgId,
  'supplier' : string,
  'createdAt' : Timestamp,
  'amount' : number,
  'billId' : bigint,
  'reason' : string,
}
export interface PurchaseOrder {
  'id' : bigint,
  'status' : PoStatus,
  'lineItems' : Array<LineItem>,
  'total' : number,
  'orgId' : OrgId,
  'supplierName' : string,
  'createdAt' : Timestamp,
  'taxTotal' : number,
  'notes' : string,
  'poNumber' : string,
  'supplierId' : bigint,
  'subtotal' : number,
}
export interface PurchaseReturn {
  'id' : bigint,
  'status' : ReturnStatus,
  'orgId' : OrgId,
  'supplier' : string,
  'createdAt' : Timestamp,
  'totalAmount' : number,
  'items' : Array<ReturnItem>,
  'returnNumber' : string,
  'billId' : bigint,
  'reason' : string,
}
export type QcResult = { 'fail' : null } |
  { 'pass' : null };
export interface QualityControl {
  'id' : QualityControlId,
  'result' : QcResult,
  'inspectionDate' : Timestamp,
  'failQty' : number,
  'orgId' : OrgId,
  'moId' : ManufacturingOrderId,
  'createdAt' : Timestamp,
  'passQty' : number,
  'enabled' : boolean,
  'defects' : Array<string>,
  'notes' : string,
  'inspector' : string,
}
export type QualityControlId = bigint;
export interface Quotation {
  'id' : bigint,
  'customerName' : string,
  'status' : QuoteStatus,
  'lineItems' : Array<LineItem>,
  'total' : number,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'taxTotal' : number,
  'quoteNumber' : string,
  'notes' : string,
  'customerId' : bigint,
  'validUntil' : Timestamp,
  'subtotal' : number,
}
export type QuoteStatus = { 'expired' : null } |
  { 'sent' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'draft' : null };
export interface RawMaterialRequisition {
  'id' : RequisitionId,
  'status' : string,
  'orgId' : OrgId,
  'approvedBy' : string,
  'moId' : ManufacturingOrderId,
  'createdAt' : Timestamp,
  'enabled' : boolean,
  'items' : Array<RequisitionItem>,
  'requestedBy' : string,
}
export type ReconciliationStatus = { 'reconciled' : string } |
  { 'unreconciled' : null };
export interface RegisterCompanyInput {
  'gst' : [] | [string],
  'pin' : string,
  'street' : string,
  'city' : string,
  'password' : string,
  'name' : string,
  'website' : [] | [string],
  'adminName' : string,
  'state' : string,
  'logoUrl' : [] | [string],
  'adminDesignation' : string,
  'adminEmail' : string,
  'companyType' : string,
  'industry' : string,
  'adminPhone' : string,
}
export interface RegisterGroupInput {
  'headName' : string,
  'password' : string,
  'name' : string,
  'description' : string,
  'contactEmail' : string,
  'phone' : string,
  'groupType' : string,
}
export interface RegisterIndividualInput {
  'password' : string,
  'fullName' : string,
  'email' : string,
  'profilePhotoUrl' : [] | [string],
  'phone' : string,
}
export type ReqItemStatus = { 'pending' : null } |
  { 'issued' : null } |
  { 'partial' : null };
export type RequisitionId = bigint;
export interface RequisitionItem {
  'status' : ReqItemStatus,
  'itemId' : bigint,
  'issuedQty' : number,
  'requiredQty' : number,
}
export interface ReturnItem {
  'qty' : number,
  'name' : string,
  'rate' : number,
  'productId' : string,
}
export type ReturnStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'draft' : null };
export type RewardType = { 'FixedAmount' : null } |
  { 'Percentage' : null };
export interface Role {
  'id' : bigint,
  'status' : RoleStatus,
  'roleName' : string,
  'screens' : Array<string>,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'description' : string,
}
export type RoleStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface RoutingOperation {
  'id' : RoutingOperationId,
  'costPerHour' : number,
  'orgId' : OrgId,
  'code' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'enabled' : boolean,
  'machineId' : MachineId,
  'standardTime' : number,
  'sequence' : bigint,
}
export type RoutingOperationId = bigint;
export interface RowError { 'msg' : string, 'row' : bigint }
export interface SalarySlip {
  'da' : number,
  'id' : bigint,
  'hra' : number,
  'status' : SlipStatus,
  'month' : bigint,
  'otherAllowances' : number,
  'orgId' : bigint,
  'createdAt' : bigint,
  'year' : bigint,
  'netPay' : number,
  'tdsDeduction' : number,
  'employeeId' : bigint,
  'esiDeduction' : number,
  'advanceDeduction' : number,
  'basicSalary' : number,
  'pfDeduction' : number,
}
export interface SaleCreditNote {
  'id' : bigint,
  'status' : NoteStatus,
  'customer' : string,
  'orgId' : OrgId,
  'creditNumber' : string,
  'createdAt' : Timestamp,
  'invoiceId' : bigint,
  'amount' : number,
  'reason' : string,
}
export interface SaleDebitNote {
  'id' : bigint,
  'status' : NoteStatus,
  'debitNumber' : string,
  'customer' : string,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'invoiceId' : bigint,
  'amount' : number,
  'reason' : string,
}
export interface SaleReturn {
  'id' : bigint,
  'status' : ReturnStatus,
  'customer' : string,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'invoiceId' : bigint,
  'totalAmount' : number,
  'items' : Array<ReturnItem>,
  'returnNumber' : string,
  'reason' : string,
}
export interface SalesOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : SoStatus,
  'lineItems' : Array<LineItem>,
  'total' : number,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'taxTotal' : number,
  'soNumber' : string,
  'notes' : string,
  'customerId' : bigint,
  'subtotal' : number,
}
export type SchemeStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface ScrapRecord {
  'id' : ScrapRecordId,
  'orgId' : OrgId,
  'scrapReason' : string,
  'date' : Timestamp,
  'moId' : ManufacturingOrderId,
  'createdAt' : Timestamp,
  'recordedBy' : string,
  'enabled' : boolean,
  'scrapQty' : number,
  'scrapValue' : number,
  'machineId' : MachineId,
}
export type ScrapRecordId = bigint;
export interface SetPermissionsInput {
  'roleName' : string,
  'screen' : string,
  'canEdit' : boolean,
  'canView' : boolean,
  'canDelete' : boolean,
  'module' : string,
  'roleId' : bigint,
  'canCreate' : boolean,
}
export interface Shipment {
  'id' : bigint,
  'weight' : [] | [number],
  'status' : ShipmentStatus,
  'deliveredAt' : [] | [bigint],
  'consigneePhone' : string,
  'orgId' : OrgId,
  'consigneeAddress' : string,
  'createdAt' : bigint,
  'trackingNo' : [] | [string],
  'consigneeName' : string,
  'dispatchedAt' : [] | [bigint],
  'orderId' : [] | [bigint],
  'updatedAt' : bigint,
  'transporterPhone' : [] | [string],
  'courierProvider' : CourierProvider,
  'dimensions' : [] | [string],
  'docId' : [] | [bigint],
  'transporterName' : [] | [string],
}
export type ShipmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'inTransit' : null } |
  { 'picked' : null } |
  { 'delivered' : null } |
  { 'returned' : null };
export interface ShopFloorControl {
  'id' : ShopFloorId,
  'startTime' : Timestamp,
  'status' : string,
  'endTime' : [] | [Timestamp],
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'workOrderId' : WorkOrderId,
  'operatorName' : string,
  'enabled' : boolean,
  'operationId' : RoutingOperationId,
  'notes' : string,
  'quantity' : number,
  'machineId' : MachineId,
}
export type ShopFloorId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SlipStatus = { 'paid' : null } |
  { 'generated' : null } |
  { 'draft' : null };
export type SoStatus = { 'cancelled' : null } |
  { 'invoiced' : null } |
  { 'confirmed' : null } |
  { 'draft' : null };
export interface StageSummary {
  'totalValue' : bigint,
  'count' : bigint,
  'stage' : DealStage,
}
export interface StockLevel {
  'id' : bigint,
  'itemId' : bigint,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'quantityOnHand' : number,
  'locationId' : [] | [bigint],
  'itemName' : string,
  'reorderLevel' : number,
  'locationName' : string,
}
export interface StripeConfig {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionStatus = { 'incomplete' : null } |
  { 'active' : null } |
  { 'canceled' : null } |
  { 'pastDue' : null } |
  { 'trialing' : null };
export interface SupplierPayment {
  'id' : bigint,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'reference' : string,
  'paymentDate' : Timestamp,
  'paymentMode' : PaymentMode,
  'amount' : number,
  'supplierId' : bigint,
  'billId' : [] | [bigint],
  'isAdvance' : boolean,
}
export interface SyncRecord {
  'status' : { 'success' : null } |
    { 'failed' : null },
  'duplicates' : bigint,
  'newLeads' : bigint,
  'timestamp' : Timestamp,
  'errorMsg' : [] | [string],
  'portal' : PortalType,
}
export interface SyncResult {
  'errors' : Array<string>,
  'duplicates' : bigint,
  'newLeads' : bigint,
  'timestamp' : Timestamp,
}
export type SyncStatus = { 'idle' : null } |
  { 'syncing' : null } |
  { 'success' : null } |
  { 'failed' : null };
export type TargetMetric = { 'Units' : null } |
  { 'NewCustomers' : null } |
  { 'Revenue' : null };
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Timestamp = bigint;
export interface TrackingEvent {
  'status' : ShipmentStatus,
  'description' : string,
  'timestamp' : bigint,
  'location' : [] | [string],
}
export interface TrackingInfo {
  'provider' : CourierProvider,
  'trackingNo' : [] | [string],
  'events' : Array<TrackingEvent>,
  'shipmentId' : bigint,
  'currentStatus' : ShipmentStatus,
}
export interface TrafficEvent {
  'id' : string,
  'referrer' : string,
  'orgId' : string,
  'userId' : string,
  'page' : string,
  'sourceType' : TrafficSource,
  'timestamp' : bigint,
  'sessionId' : string,
}
export interface TrafficQuery {
  'dateTo' : [] | [bigint],
  'orgId' : string,
  'page' : [] | [string],
  'sourceType' : [] | [TrafficSource],
  'dateFrom' : [] | [bigint],
}
export type TrafficSource = { 'internal' : null } |
  { 'direct' : null } |
  { 'external' : null };
export interface TrafficSummary {
  'topPages' : Array<[string, bigint]>,
  'totalToday' : bigint,
  'internalToday' : bigint,
  'externalToday' : bigint,
  'topReferrers' : Array<[string, bigint]>,
  'directToday' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'orgId' : OrgId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'description' : string,
  'category' : TransactionCategory,
  'amount' : bigint,
  'reconciliation' : ReconciliationStatus,
}
export type TransactionCategory = { 'revenue' : null } |
  { 'other' : null } |
  { 'equipment' : null } |
  { 'travel' : null } |
  { 'software' : null } |
  { 'contractorFees' : null };
export interface TransactionFilter {
  'reconciled' : [] | [boolean],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'category' : [] | [TransactionCategory],
}
export interface TransactionInput {
  'date' : Timestamp,
  'description' : string,
  'category' : TransactionCategory,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UnitOfMeasure {
  'id' : bigint,
  'baseUnit' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Timestamp,
  'conversionFactor' : number,
  'symbol' : string,
}
export interface UpdateAttendanceInput {
  'id' : bigint,
  'totalHours' : number,
  'date' : string,
  'punchOut' : [] | [string],
  'attendanceType' : AttendanceType,
  'employeeId' : bigint,
  'punchIn' : [] | [string],
  'notes' : string,
}
export interface UpdateBomInput {
  'id' : BomId,
  'status' : string,
  'components' : Array<BomComponent>,
  'productName' : string,
  'enabled' : boolean,
  'revision' : string,
}
export interface UpdateCategoryInput {
  'id' : CategoryId,
  'orgId' : OrgId,
  'name' : string,
  'description' : string,
}
export interface UpdateCostOfProductionInput {
  'id' : CostOfProductionId,
  'period' : string,
  'moId' : ManufacturingOrderId,
  'enabled' : boolean,
  'labourCost' : number,
  'notes' : string,
  'scrapCost' : number,
  'materialCost' : number,
  'overheadCost' : number,
}
export interface UpdateEmployeeInput {
  'id' : bigint,
  'status' : EmployeeStatus,
  'employeeCode' : string,
  'name' : string,
  'designation' : string,
  'joiningDate' : string,
  'email' : string,
  'salaryGrade' : string,
  'enabled' : boolean,
  'phone' : string,
  'department' : string,
}
export interface UpdateFinanceCategoryInput {
  'id' : string,
  'categoryType' : FinanceCategoryType,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'parentId' : [] | [string],
}
export interface UpdateFinishedGoodInput {
  'id' : FinishedGoodId,
  'status' : string,
  'expiryDate' : [] | [Timestamp],
  'moId' : ManufacturingOrderId,
  'productId' : bigint,
  'productionDate' : Timestamp,
  'enabled' : boolean,
  'warehouseLocation' : string,
  'quantity' : number,
  'batchNo' : string,
}
export interface UpdateGroupInput {
  'id' : bigint,
  'status' : GroupStatus,
  'parentGroup' : [] | [bigint],
  'description' : string,
  'groupName' : string,
}
export interface UpdateHsnSacCodeInput {
  'id' : string,
  'name' : string,
  'description' : string,
  'hsnCode' : [] | [string],
  'isActive' : boolean,
  'codeType' : HsnSacCodeType,
  'sacCode' : [] | [string],
  'category' : string,
}
export interface UpdateIncentiveSchemeInput {
  'id' : bigint,
  'status' : SchemeStatus,
  'rewardValue' : number,
  'effectiveTo' : [] | [Timestamp],
  'schemeName' : string,
  'rewardType' : RewardType,
  'category' : string,
  'targetValue' : number,
  'targetMetric' : TargetMetric,
  'effectiveFrom' : Timestamp,
}
export interface UpdateInventoryCategoryInput {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'parentId' : [] | [bigint],
}
export interface UpdateInvoiceInput {
  'id' : InvoiceId,
  'lineItems' : Array<LineItem__2>,
  'taxPercent' : number,
  'dueDate' : Timestamp,
  'currency' : string,
  'notes' : [] | [string],
  'billTo' : BillTo,
}
export interface UpdateItemMasterInput {
  'id' : bigint,
  'categoryId' : [] | [bigint],
  'enableSerial' : boolean,
  'categoryName' : string,
  'partNumber' : string,
  'name' : string,
  'rate' : number,
  'uomName' : string,
  'description' : string,
  'hsnCode' : string,
  'enableShelfLife' : boolean,
  'enableBatch' : boolean,
  'taxPct' : number,
  'attributes' : Array<ItemAttribute_>,
  'barcode' : string,
  'itemCode' : string,
  'uomId' : [] | [bigint],
}
export interface UpdateLocationInput {
  'id' : bigint,
  'email' : string,
  'state' : string,
  'locationCode' : string,
  'locationName' : string,
}
export interface UpdateMachineInput {
  'id' : MachineId,
  'status' : MachineStatus,
  'code' : string,
  'lastMaintenance' : [] | [Timestamp],
  'name' : string,
  'enabled' : boolean,
  'capacityUnit' : string,
  'capacity' : number,
  'location' : string,
  'machineType' : string,
}
export interface UpdateManufacturingOrderInput {
  'id' : ManufacturingOrderId,
  'status' : MoStatus,
  'dueDate' : Timestamp,
  'workOrderId' : WorkOrderId,
  'enabled' : boolean,
  'quantity' : number,
  'completedQty' : number,
  'startDate' : Timestamp,
}
export interface UpdateOrgConfigurationInput {
  'enableSerialization' : boolean,
  'trackInventory' : boolean,
  'enableBatches' : boolean,
  'invoiceTemplate' : string,
  'enableShelfLife' : boolean,
  'logoUrl' : string,
  'dateFormat' : string,
  'paymentGatewayKey' : string,
  'paymentGatewayType' : string,
  'enableBarcoding' : boolean,
  'currency' : string,
  'numberSeriesInvoice' : string,
  'taxAdjustment' : number,
  'numberSeriesPO' : string,
  'numberSeriesSO' : string,
}
export interface UpdateProductInput {
  'id' : ProductId,
  'categoryId' : [] | [CategoryId],
  'taxPercent' : bigint,
  'stockQty' : bigint,
  'partNumber' : string,
  'orgId' : OrgId,
  'name' : string,
  'rate' : number,
  'unit' : string,
  'description' : string,
  'hsnCode' : string,
}
export interface UpdateProductionPlanInput {
  'id' : ProductionPlanId,
  'status' : string,
  'period' : string,
  'targetQty' : number,
  'enabled' : boolean,
  'actualQty' : number,
  'workOrderIds' : Array<WorkOrderId>,
}
export interface UpdatePurchaseBillInput {
  'id' : bigint,
  'lineItems' : Array<LineItem>,
  'supplierName' : string,
  'dueDate' : Timestamp,
  'amountPaid' : number,
  'notes' : string,
  'supplierId' : bigint,
}
export interface UpdatePurchaseOrderInput {
  'id' : bigint,
  'lineItems' : Array<LineItem>,
  'supplierName' : string,
  'notes' : string,
  'supplierId' : bigint,
}
export interface UpdateQualityControlInput {
  'id' : QualityControlId,
  'result' : QcResult,
  'inspectionDate' : Timestamp,
  'failQty' : number,
  'moId' : ManufacturingOrderId,
  'passQty' : number,
  'enabled' : boolean,
  'defects' : Array<string>,
  'notes' : string,
  'inspector' : string,
}
export interface UpdateQuotationInput {
  'id' : bigint,
  'customerName' : string,
  'lineItems' : Array<LineItem>,
  'notes' : string,
  'customerId' : bigint,
  'validUntil' : Timestamp,
}
export interface UpdateRequisitionInput {
  'id' : RequisitionId,
  'status' : string,
  'approvedBy' : string,
  'moId' : ManufacturingOrderId,
  'enabled' : boolean,
  'items' : Array<RequisitionItem>,
  'requestedBy' : string,
}
export interface UpdateRoleInput {
  'id' : bigint,
  'status' : RoleStatus,
  'roleName' : string,
  'screens' : Array<string>,
  'description' : string,
}
export interface UpdateRoutingOperationInput {
  'id' : RoutingOperationId,
  'costPerHour' : number,
  'code' : string,
  'name' : string,
  'description' : string,
  'enabled' : boolean,
  'machineId' : MachineId,
  'standardTime' : number,
  'sequence' : bigint,
}
export interface UpdateSalesOrderInput {
  'id' : bigint,
  'customerName' : string,
  'lineItems' : Array<LineItem>,
  'notes' : string,
  'customerId' : bigint,
}
export interface UpdateScrapRecordInput {
  'id' : ScrapRecordId,
  'scrapReason' : string,
  'date' : Timestamp,
  'moId' : ManufacturingOrderId,
  'recordedBy' : string,
  'enabled' : boolean,
  'scrapQty' : number,
  'scrapValue' : number,
  'machineId' : MachineId,
}
export interface UpdateShipmentInput {
  'weight' : [] | [number],
  'status' : [] | [ShipmentStatus],
  'consigneePhone' : [] | [string],
  'consigneeAddress' : [] | [string],
  'trackingNo' : [] | [string],
  'consigneeName' : [] | [string],
  'orderId' : [] | [bigint],
  'transporterPhone' : [] | [string],
  'courierProvider' : [] | [CourierProvider],
  'dimensions' : [] | [string],
  'docId' : [] | [bigint],
  'transporterName' : [] | [string],
}
export interface UpdateShopFloorInput {
  'id' : ShopFloorId,
  'startTime' : Timestamp,
  'status' : string,
  'endTime' : [] | [Timestamp],
  'workOrderId' : WorkOrderId,
  'operatorName' : string,
  'enabled' : boolean,
  'operationId' : RoutingOperationId,
  'notes' : string,
  'quantity' : number,
  'machineId' : MachineId,
}
export interface UpdateSlipInput {
  'da' : number,
  'id' : bigint,
  'hra' : number,
  'status' : SlipStatus,
  'otherAllowances' : number,
  'tdsDeduction' : number,
  'esiDeduction' : number,
  'advanceDeduction' : number,
  'basicSalary' : number,
  'pfDeduction' : number,
}
export interface UpdateStockLevelInput {
  'itemId' : bigint,
  'quantityOnHand' : number,
  'locationId' : [] | [bigint],
  'reorderLevel' : number,
  'locationName' : string,
}
export interface UpdateWorkOrderInput {
  'id' : WorkOrderId,
  'status' : WorkOrderStatus,
  'plannedEnd' : Timestamp,
  'enabled' : boolean,
  'notes' : string,
  'quantity' : number,
  'plannedStart' : Timestamp,
  'bomId' : BomId,
  'actualEnd' : [] | [Timestamp],
  'actualStart' : [] | [Timestamp],
}
export interface UpsertPfEsiInput {
  'insurancePremiumPerEmployee' : number,
  'esiRate' : number,
  'pfEmployerRate' : number,
  'pfEmployeeRate' : number,
  'effectiveFrom' : string,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserRoleAssignment {
  'id' : bigint,
  'roleName' : string,
  'assignedAt' : Timestamp,
  'orgId' : OrgId,
  'userId' : Principal,
  'roleId' : bigint,
}
export interface WorkOrder {
  'id' : WorkOrderId,
  'status' : WorkOrderStatus,
  'plannedEnd' : Timestamp,
  'orgId' : OrgId,
  'createdAt' : Timestamp,
  'enabled' : boolean,
  'notes' : string,
  'quantity' : number,
  'plannedStart' : Timestamp,
  'bomId' : BomId,
  'actualEnd' : [] | [Timestamp],
  'actualStart' : [] | [Timestamp],
}
export type WorkOrderId = bigint;
export type WorkOrderStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptInvite' : ActorMethod<[bigint], undefined>,
  'acknowledgeGstReturn' : ActorMethod<[GstReturnId, OrgId], [] | [GstReturn]>,
  'addDealNote' : ActorMethod<[OrgId, DealNoteInput], NoteId>,
  'addInteractionNote' : ActorMethod<[OrgId, InteractionNoteInput], NoteId>,
  'addTransaction' : ActorMethod<[OrgId, TransactionInput], Transaction>,
  'approvePurchaseOrder' : ActorMethod<[OrgId, bigint], PurchaseOrder>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[OrgId, AssignRoleInput], UserRoleAssignment>,
  'bulkImportProducts' : ActorMethod<
    [Array<CreateProductInput>],
    { 'ok' : BulkImportResult } |
      { 'notAuthorized' : null }
  >,
  'cancelInvite' : ActorMethod<[bigint], undefined>,
  'changePlan' : ActorMethod<[OrgId, PlanTier], undefined>,
  'checkInvoicePaymentStatus' : ActorMethod<[OrgId, InvoiceId], string>,
  'confirmSalesOrder' : ActorMethod<[OrgId, bigint], SalesOrder>,
  'confirmSubscription' : ActorMethod<[OrgId, string], undefined>,
  'convertQuotationToSalesOrder' : ActorMethod<[OrgId, bigint], SalesOrder>,
  'createAdminNotification' : ActorMethod<
    [CreateNotificationInput],
    AdminNotification
  >,
  'createBom' : ActorMethod<[OrgId, CreateBomInput], BillOfMaterial>,
  'createCategory' : ActorMethod<
    [CreateCategoryInput],
    { 'ok' : Category } |
      { 'notAuthorized' : null }
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createContact' : ActorMethod<[OrgId, ContactInput], ContactId>,
  'createCostOfProduction' : ActorMethod<
    [OrgId, CreateCostOfProductionInput],
    CostOfProduction
  >,
  'createCustomerReceipt' : ActorMethod<
    [OrgId, CreateReceiptInput],
    CustomerReceipt
  >,
  'createDeal' : ActorMethod<[OrgId, DealInput], DealId>,
  'createExtendedLead' : ActorMethod<[OrgId, ExtendedLeadInput], ExtendedLead>,
  'createFinanceCategory' : ActorMethod<
    [OrgId, CreateFinanceCategoryInput],
    FinanceCategory
  >,
  'createFinishedGood' : ActorMethod<
    [OrgId, CreateFinishedGoodInput],
    FinishedGood
  >,
  'createGroup' : ActorMethod<[OrgId, CreateGroupInput], Group_>,
  'createHsnSacCode' : ActorMethod<[OrgId, CreateHsnSacCodeInput], HsnSacCode>,
  'createIncentiveScheme' : ActorMethod<
    [OrgId, CreateIncentiveSchemeInput],
    IncentiveScheme
  >,
  'createInventoryCategory' : ActorMethod<
    [OrgId, CreateInventoryCategoryInput],
    InventoryCategory
  >,
  'createInvoice' : ActorMethod<[OrgId, CreateInvoiceInput], InvoiceView>,
  'createItemAttribute' : ActorMethod<
    [OrgId, CreateItemAttributeInput],
    ItemAttributeDef
  >,
  'createItemMaster' : ActorMethod<[OrgId, CreateItemMasterInput], ItemMaster>,
  'createLead' : ActorMethod<[OrgId, LeadInput], LeadId>,
  'createLocation' : ActorMethod<[OrgId, CreateLocationInput], Location>,
  'createMachine' : ActorMethod<[OrgId, CreateMachineInput], Machine>,
  'createManufacturingOrder' : ActorMethod<
    [OrgId, CreateManufacturingOrderInput],
    ManufacturingOrder
  >,
  'createOrg' : ActorMethod<
    [
      string,
      string,
      string,
      OrgType,
      [] | [string],
      [] | [string],
      [] | [OrgAddress],
      [] | [OrgContactPerson],
    ],
    OrgId
  >,
  'createPortalEmployee' : ActorMethod<
    [CreateEmployeeInput__1],
    { 'ok' : PortalEmployee } |
      { 'err' : string }
  >,
  'createPortalTask' : ActorMethod<[CreateTaskInput], PortalTask>,
  'createPosTransaction' : ActorMethod<
    [OrgId, CreatePosTransactionInput],
    PosTransaction
  >,
  'createProduct' : ActorMethod<
    [CreateProductInput],
    { 'ok' : Product } |
      { 'notAuthorized' : null }
  >,
  'createProductionPlan' : ActorMethod<
    [OrgId, CreateProductionPlanInput],
    ProductionPlan
  >,
  'createPurchaseBill' : ActorMethod<
    [OrgId, CreatePurchaseBillInput],
    PurchaseBill
  >,
  'createPurchaseCreditNote' : ActorMethod<
    [OrgId, CreateCreditNoteInput__1],
    PurchaseCreditNote
  >,
  'createPurchaseDebitNote' : ActorMethod<
    [OrgId, CreateDebitNoteInput__1],
    PurchaseDebitNote
  >,
  'createPurchaseOrder' : ActorMethod<
    [OrgId, CreatePurchaseOrderInput],
    PurchaseOrder
  >,
  'createPurchaseReturn' : ActorMethod<
    [OrgId, CreatePurchaseReturnInput],
    PurchaseReturn
  >,
  'createQualityControl' : ActorMethod<
    [OrgId, CreateQualityControlInput],
    QualityControl
  >,
  'createQuotation' : ActorMethod<[OrgId, CreateQuotationInput], Quotation>,
  'createRawMaterialRequisition' : ActorMethod<
    [OrgId, CreateRequisitionInput],
    RawMaterialRequisition
  >,
  'createRefundRequest' : ActorMethod<
    [CreateRefundRequestInput],
    GstRefundRequest
  >,
  'createRole' : ActorMethod<[OrgId, CreateRoleInput], Role>,
  'createRoutingOperation' : ActorMethod<
    [OrgId, CreateRoutingOperationInput],
    RoutingOperation
  >,
  'createSaleCreditNote' : ActorMethod<
    [OrgId, CreateCreditNoteInput],
    SaleCreditNote
  >,
  'createSaleDebitNote' : ActorMethod<
    [OrgId, CreateDebitNoteInput],
    SaleDebitNote
  >,
  'createSaleReturn' : ActorMethod<[OrgId, CreateSaleReturnInput], SaleReturn>,
  'createSalesOrder' : ActorMethod<[OrgId, CreateSalesOrderInput], SalesOrder>,
  'createScrapRecord' : ActorMethod<
    [OrgId, CreateScrapRecordInput],
    ScrapRecord
  >,
  'createShipment' : ActorMethod<[OrgId, CreateShipmentInput], Shipment>,
  'createShopFloorControl' : ActorMethod<
    [OrgId, CreateShopFloorInput],
    ShopFloorControl
  >,
  'createSubscriptionCheckout' : ActorMethod<
    [OrgId, PlanTier, string, string],
    string
  >,
  'createSupplierPayment' : ActorMethod<
    [OrgId, CreateSupplierPaymentInput],
    SupplierPayment
  >,
  'createUom' : ActorMethod<[OrgId, CreateUomInput], UnitOfMeasure>,
  'createWorkOrder' : ActorMethod<[OrgId, CreateWorkOrderInput], WorkOrder>,
  'deactivatePortalEmployee' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deductProductStock' : ActorMethod<[ProductId, OrgId, bigint], boolean>,
  'deleteBom' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteCategory' : ActorMethod<
    [OrgId, CategoryId],
    { 'ok' : null } |
      { 'notAuthorized' : null } |
      { 'notFound' : null }
  >,
  'deleteContact' : ActorMethod<[OrgId, ContactId], boolean>,
  'deleteCostOfProduction' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteDeal' : ActorMethod<[OrgId, DealId], boolean>,
  'deleteFinanceCategory' : ActorMethod<[OrgId, string], boolean>,
  'deleteFinishedGood' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteGroup' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteHsnSacCode' : ActorMethod<[OrgId, string], boolean>,
  'deleteIncentiveScheme' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteInventoryCategory' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteItemAttribute' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteItemMaster' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteLocation' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteMachine' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteManufacturingOrder' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteNotification' : ActorMethod<[NotificationId], boolean>,
  'deleteOrg' : ActorMethod<[OrgId], undefined>,
  'deletePortalTask' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<
    [OrgId, ProductId],
    { 'ok' : null } |
      { 'notAuthorized' : null } |
      { 'notFound' : null }
  >,
  'deleteProductionPlan' : ActorMethod<[OrgId, bigint], undefined>,
  'deletePurchaseBill' : ActorMethod<[OrgId, bigint], undefined>,
  'deletePurchaseOrder' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteQualityControl' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteRawMaterialRequisition' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteRole' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteRoutingOperation' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteScrapRecord' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteShipment' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteShopFloorControl' : ActorMethod<[OrgId, bigint], undefined>,
  'deleteTrafficEvents' : ActorMethod<
    [string, Array<string>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'deleteUom' : ActorMethod<[OrgId, bigint], boolean>,
  'deleteWorkOrder' : ActorMethod<[OrgId, bigint], undefined>,
  'exportContactsCsv' : ActorMethod<[OrgId], string>,
  'generateGstReturn' : ActorMethod<
    [OrgId, bigint, bigint, GstReturnType],
    GstReturn
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashFlowForecast' : ActorMethod<[OrgId], Array<CashFlowForecast>>,
  'getContact' : ActorMethod<[OrgId, ContactId], [] | [Contact]>,
  'getDeal' : ActorMethod<[OrgId, DealId], [] | [Deal]>,
  'getErpModuleEnabled' : ActorMethod<[OrgId], boolean>,
  'getFinanceDashboard' : ActorMethod<[OrgId], FinanceDashboard>,
  'getGstReturn' : ActorMethod<[GstReturnId, OrgId], [] | [GstReturn]>,
  'getInvoice' : ActorMethod<[OrgId, InvoiceId], [] | [InvoiceView]>,
  'getItemMaster' : ActorMethod<[OrgId, bigint], [] | [ItemMaster]>,
  'getLeadByContact' : ActorMethod<[OrgId, ContactId], [] | [Lead]>,
  'getModuleVisibility' : ActorMethod<[OrgId], Array<[string, boolean]>>,
  'getMonthlySummary' : ActorMethod<[OrgId, bigint, bigint], MonthlySummary>,
  'getMyRole' : ActorMethod<[OrgId], [] | [OrgRole]>,
  'getOrg' : ActorMethod<[OrgId], Org>,
  'getOrgBillingInfo' : ActorMethod<[OrgId], [] | [OrgBillingInfo]>,
  'getOrgConfiguration' : ActorMethod<[OrgId], OrgConfiguration>,
  'getOrgSubscription' : ActorMethod<[OrgId], [] | [OrgSubscription]>,
  'getPipelineSummary' : ActorMethod<[OrgId], PipelineSummary>,
  'getPortalApiKeys' : ActorMethod<[OrgId], Array<PortalApiKeyInfo>>,
  'getPortalDashboardLayout' : ActorMethod<[string], [] | [DashboardLayout]>,
  'getProduct' : ActorMethod<
    [OrgId, ProductId],
    { 'ok' : Product } |
      { 'notAuthorized' : null } |
      { 'notFound' : null }
  >,
  'getRefundRequest' : ActorMethod<[OrgId, bigint], [] | [GstRefundRequest]>,
  'getShipment' : ActorMethod<[OrgId, bigint], [] | [Shipment]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscription' : ActorMethod<[OrgId], [] | [OrgSubscription]>,
  'getTrafficSummary' : ActorMethod<
    [string],
    { 'ok' : TrafficSummary } |
      { 'err' : string }
  >,
  'getUnreadCount' : ActorMethod<[OrgId__15], bigint>,
  'getWorkOrder' : ActorMethod<[OrgId, bigint], [] | [WorkOrder]>,
  'hrCreateAttendance' : ActorMethod<
    [bigint, CreateAttendanceInput],
    Attendance
  >,
  'hrCreateEmployee' : ActorMethod<[bigint, CreateEmployeeInput], Employee>,
  'hrCreateSlip' : ActorMethod<[bigint, CreateSlipInput], SalarySlip>,
  'hrDeleteAttendance' : ActorMethod<[bigint, bigint], undefined>,
  'hrDeleteEmployee' : ActorMethod<[bigint, bigint], undefined>,
  'hrDeleteSlip' : ActorMethod<[bigint, bigint], undefined>,
  'hrGetEmployee' : ActorMethod<[bigint, bigint], [] | [Employee]>,
  'hrGetPfEsiConfig' : ActorMethod<[bigint], [] | [PfEsiConfig]>,
  'hrListAttendance' : ActorMethod<[bigint, [] | [bigint]], Array<Attendance>>,
  'hrListEmployees' : ActorMethod<[bigint], Array<Employee>>,
  'hrListPayrolls' : ActorMethod<[bigint], Array<Payroll>>,
  'hrListSlips' : ActorMethod<[bigint, [] | [bigint]], Array<SalarySlip>>,
  'hrProcessPayroll' : ActorMethod<[bigint, CreatePayrollInput], Payroll>,
  'hrToggleEmployee' : ActorMethod<[bigint, bigint], Employee>,
  'hrUpdateAttendance' : ActorMethod<
    [bigint, UpdateAttendanceInput],
    Attendance
  >,
  'hrUpdateEmployee' : ActorMethod<[bigint, UpdateEmployeeInput], Employee>,
  'hrUpdatePayrollStatus' : ActorMethod<
    [bigint, bigint, PayrollStatus],
    Payroll
  >,
  'hrUpdateSlip' : ActorMethod<[bigint, UpdateSlipInput], SalarySlip>,
  'hrUpsertPfEsiConfig' : ActorMethod<[bigint, UpsertPfEsiInput], PfEsiConfig>,
  'importLeadsFromCsv' : ActorMethod<[OrgId, Array<CsvLeadRow>], ImportResult>,
  'inviteMember' : ActorMethod<[OrgId, string, OrgRole], PendingInvite>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isInvoiceStripeConfigured' : ActorMethod<[OrgId], boolean>,
  'isSlugAvailable' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAdminNotifications' : ActorMethod<
    [string, string],
    Array<AdminNotification>
  >,
  'listBillingHistory' : ActorMethod<[OrgId], Array<BillingEntry>>,
  'listBoms' : ActorMethod<[OrgId], Array<BillOfMaterial>>,
  'listCategories' : ActorMethod<
    [OrgId],
    { 'ok' : Array<Category> } |
      { 'notAuthorized' : null }
  >,
  'listContacts' : ActorMethod<
    [OrgId, [] | [string], [] | [string], [] | [ContactSortField], boolean],
    Array<Contact>
  >,
  'listCostsOfProduction' : ActorMethod<[OrgId], Array<CostOfProduction>>,
  'listCustomerReceipts' : ActorMethod<[OrgId], Array<CustomerReceipt>>,
  'listDealNotes' : ActorMethod<[OrgId, DealId], Array<DealNote>>,
  'listDealStageHistory' : ActorMethod<[OrgId, DealId], Array<DealStageEvent>>,
  'listDeals' : ActorMethod<[OrgId], Array<Deal>>,
  'listFinanceCategories' : ActorMethod<
    [OrgId, FinanceCategoryFilter],
    Array<FinanceCategory>
  >,
  'listFinishedGoods' : ActorMethod<[OrgId], Array<FinishedGood>>,
  'listGroups' : ActorMethod<[OrgId], Array<Group_>>,
  'listGstReturns' : ActorMethod<[OrgId], Array<GstReturn>>,
  'listHsnSacCodes' : ActorMethod<[OrgId, HsnSacFilter], Array<HsnSacCode>>,
  'listIncentiveSchemes' : ActorMethod<[OrgId], Array<IncentiveScheme>>,
  'listInteractionNotes' : ActorMethod<
    [OrgId, ContactId],
    Array<InteractionNote>
  >,
  'listInventoryCategories' : ActorMethod<
    [OrgId, [] | [[] | [bigint]]],
    Array<InventoryCategory>
  >,
  'listInvoices' : ActorMethod<[OrgId], Array<InvoiceView>>,
  'listItemAttributes' : ActorMethod<[OrgId], Array<ItemAttributeDef>>,
  'listItemMasters' : ActorMethod<[OrgId, [] | [string]], Array<ItemMaster>>,
  'listLeads' : ActorMethod<[OrgId, [] | [LeadStatus]], Array<ExtendedLead>>,
  'listLocations' : ActorMethod<[OrgId], Array<Location>>,
  'listMachines' : ActorMethod<[OrgId], Array<Machine>>,
  'listManufacturingOrders' : ActorMethod<[OrgId], Array<ManufacturingOrder>>,
  'listMembers' : ActorMethod<[OrgId], Array<OrgMember>>,
  'listMyOrgs' : ActorMethod<[], Array<OrgSummary>>,
  'listNotifications' : ActorMethod<[OrgId__15], Array<Notification>>,
  'listPendingInvites' : ActorMethod<[OrgId], Array<PendingInvite>>,
  'listPermissions' : ActorMethod<[OrgId, [] | [bigint]], Array<Permission>>,
  'listPortalEmployees' : ActorMethod<[string], Array<PortalEmployee>>,
  'listPortalSyncHistory' : ActorMethod<[OrgId, PortalType], Array<SyncRecord>>,
  'listPortalTasks' : ActorMethod<[string, [] | [string]], Array<PortalTask>>,
  'listPosTransactions' : ActorMethod<[OrgId], Array<PosTransaction>>,
  'listProductionPlans' : ActorMethod<[OrgId], Array<ProductionPlan>>,
  'listProducts' : ActorMethod<
    [OrgId],
    { 'ok' : Array<Product> } |
      { 'notAuthorized' : null }
  >,
  'listPurchaseBills' : ActorMethod<[OrgId], Array<PurchaseBill>>,
  'listPurchaseCreditNotes' : ActorMethod<[OrgId], Array<PurchaseCreditNote>>,
  'listPurchaseDebitNotes' : ActorMethod<[OrgId], Array<PurchaseDebitNote>>,
  'listPurchaseOrders' : ActorMethod<[OrgId], Array<PurchaseOrder>>,
  'listPurchaseReturns' : ActorMethod<[OrgId], Array<PurchaseReturn>>,
  'listQualityControls' : ActorMethod<[OrgId], Array<QualityControl>>,
  'listQuotations' : ActorMethod<[OrgId], Array<Quotation>>,
  'listRawMaterialRequisitions' : ActorMethod<
    [OrgId],
    Array<RawMaterialRequisition>
  >,
  'listRefundRequests' : ActorMethod<[OrgId], Array<GstRefundRequest>>,
  'listRoles' : ActorMethod<[OrgId], Array<Role>>,
  'listRoutingOperations' : ActorMethod<[OrgId], Array<RoutingOperation>>,
  'listSaleCreditNotes' : ActorMethod<[OrgId], Array<SaleCreditNote>>,
  'listSaleDebitNotes' : ActorMethod<[OrgId], Array<SaleDebitNote>>,
  'listSaleReturns' : ActorMethod<[OrgId], Array<SaleReturn>>,
  'listSalesOrders' : ActorMethod<[OrgId], Array<SalesOrder>>,
  'listScrapRecords' : ActorMethod<[OrgId], Array<ScrapRecord>>,
  'listShipments' : ActorMethod<
    [OrgId, [] | [ShipmentStatus], [] | [bigint], [] | [bigint]],
    Array<Shipment>
  >,
  'listShopFloorControls' : ActorMethod<[OrgId], Array<ShopFloorControl>>,
  'listStockLevels' : ActorMethod<[OrgId, [] | [bigint]], Array<StockLevel>>,
  'listSupplierPayments' : ActorMethod<[OrgId], Array<SupplierPayment>>,
  'listTransactions' : ActorMethod<
    [OrgId, TransactionFilter],
    Array<LedgerEntry>
  >,
  'listUoms' : ActorMethod<[OrgId], Array<UnitOfMeasure>>,
  'listUserRoleAssignments' : ActorMethod<
    [OrgId, [] | [Principal]],
    Array<UserRoleAssignment>
  >,
  'listWorkOrders' : ActorMethod<[OrgId], Array<WorkOrder>>,
  'logTraffic' : ActorMethod<
    [string, string, string, TrafficSource, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'loginPortalAdmin' : ActorMethod<
    [string, string],
    { 'ok' : PortalAdminSession } |
      { 'err' : string }
  >,
  'loginPortalEmployee' : ActorMethod<
    [string, string],
    { 'ok' : PortalEmployeeSession } |
      { 'err' : string }
  >,
  'markAllNotificationsRead' : ActorMethod<[OrgId__15], bigint>,
  'markInvoicePaid' : ActorMethod<[OrgId, InvoiceId], InvoiceView>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'markPortalNotificationRead' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'publishNotification' : ActorMethod<
    [OrgId__15, NotifType, string, string],
    NotificationId
  >,
  'purgeTrafficEvents' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'queryTrafficReport' : ActorMethod<
    [TrafficQuery],
    { 'ok' : Array<TrafficEvent> } |
      { 'err' : string }
  >,
  'registerPortalCompany' : ActorMethod<
    [RegisterCompanyInput],
    { 'ok' : PortalAdminSession } |
      { 'err' : string }
  >,
  'registerPortalGroup' : ActorMethod<
    [RegisterGroupInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'registerPortalIndividual' : ActorMethod<
    [RegisterIndividualInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeMember' : ActorMethod<[OrgId, Principal], undefined>,
  'revokeUserRole' : ActorMethod<[OrgId, bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePortalApiKey' : ActorMethod<[OrgId, PortalType, string], undefined>,
  'savePortalDashboardLayout' : ActorMethod<[string, string], DashboardLayout>,
  'searchByHsn' : ActorMethod<[OrgId, string], Array<Product>>,
  'searchByPartNumber' : ActorMethod<[OrgId, string], Array<Product>>,
  'sendInvoice' : ActorMethod<[OrgId, InvoiceId, string, string], string>,
  'setErpModuleEnabled' : ActorMethod<[OrgId, boolean], undefined>,
  'setInvoiceStripeConfig' : ActorMethod<[OrgId, StripeConfig], undefined>,
  'setModuleVisibility' : ActorMethod<[OrgId, string, boolean], undefined>,
  'setOrgBillingInfo' : ActorMethod<[OrgId, OrgBillingInfo], undefined>,
  'setOrgSubscription' : ActorMethod<[OrgId, OrgSubscription], undefined>,
  'setPermission' : ActorMethod<[OrgId, SetPermissionsInput], Permission>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitGstReturn' : ActorMethod<[GstReturnId, OrgId], [] | [GstReturn]>,
  'subscribeToNotifications' : ActorMethod<[OrgId__15], undefined>,
  'syncPortalLeads' : ActorMethod<[OrgId, PortalType], SyncResult>,
  'trackShipment' : ActorMethod<[OrgId, bigint], [] | [TrackingInfo]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformInvoice' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'updateBom' : ActorMethod<[OrgId, UpdateBomInput], BillOfMaterial>,
  'updateCategory' : ActorMethod<
    [UpdateCategoryInput],
    { 'ok' : Category } |
      { 'notAuthorized' : null } |
      { 'notFound' : null }
  >,
  'updateContact' : ActorMethod<[OrgId, ContactId, ContactInput], boolean>,
  'updateCostOfProduction' : ActorMethod<
    [OrgId, UpdateCostOfProductionInput],
    CostOfProduction
  >,
  'updateDeal' : ActorMethod<[OrgId, DealId, DealInput], boolean>,
  'updateExtendedLeadStatus' : ActorMethod<
    [OrgId, LeadId, LeadStatus],
    boolean
  >,
  'updateFinanceCategory' : ActorMethod<
    [OrgId, UpdateFinanceCategoryInput],
    [] | [FinanceCategory]
  >,
  'updateFinishedGood' : ActorMethod<
    [OrgId, UpdateFinishedGoodInput],
    FinishedGood
  >,
  'updateGroup' : ActorMethod<[OrgId, UpdateGroupInput], [] | [Group_]>,
  'updateHsnSacCode' : ActorMethod<
    [OrgId, UpdateHsnSacCodeInput],
    [] | [HsnSacCode]
  >,
  'updateIncentiveScheme' : ActorMethod<
    [OrgId, UpdateIncentiveSchemeInput],
    IncentiveScheme
  >,
  'updateInventoryCategory' : ActorMethod<
    [OrgId, UpdateInventoryCategoryInput],
    [] | [InventoryCategory]
  >,
  'updateInvoice' : ActorMethod<[OrgId, UpdateInvoiceInput], InvoiceView>,
  'updateItemMaster' : ActorMethod<
    [OrgId, UpdateItemMasterInput],
    [] | [ItemMaster]
  >,
  'updateLocation' : ActorMethod<[OrgId, UpdateLocationInput], [] | [Location]>,
  'updateMachine' : ActorMethod<[OrgId, UpdateMachineInput], Machine>,
  'updateManufacturingOrder' : ActorMethod<
    [OrgId, UpdateManufacturingOrderInput],
    ManufacturingOrder
  >,
  'updateMemberRole' : ActorMethod<[OrgId, Principal, OrgRole], undefined>,
  'updateOrg' : ActorMethod<
    [
      OrgId,
      string,
      string,
      string,
      OrgType,
      [] | [string],
      [] | [string],
      [] | [OrgAddress],
      [] | [OrgContactPerson],
    ],
    undefined
  >,
  'updateOrgConfiguration' : ActorMethod<
    [OrgId, UpdateOrgConfigurationInput],
    OrgConfiguration
  >,
  'updatePortalEmployee' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [Array<[string, boolean]>],
    ],
    { 'ok' : PortalEmployee } |
      { 'err' : string }
  >,
  'updatePortalTask' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [TaskPriority],
      [] | [bigint],
      [] | [string],
    ],
    { 'ok' : PortalTask } |
      { 'err' : string }
  >,
  'updatePortalTaskStatus' : ActorMethod<
    [string, TaskStatus],
    { 'ok' : PortalTask } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [UpdateProductInput],
    { 'ok' : Product } |
      { 'notAuthorized' : null } |
      { 'notFound' : null }
  >,
  'updateProductionPlan' : ActorMethod<
    [OrgId, UpdateProductionPlanInput],
    ProductionPlan
  >,
  'updatePurchaseBill' : ActorMethod<
    [OrgId, UpdatePurchaseBillInput],
    PurchaseBill
  >,
  'updatePurchaseOrder' : ActorMethod<
    [OrgId, UpdatePurchaseOrderInput],
    PurchaseOrder
  >,
  'updateQualityControl' : ActorMethod<
    [OrgId, UpdateQualityControlInput],
    QualityControl
  >,
  'updateQuotation' : ActorMethod<[OrgId, UpdateQuotationInput], Quotation>,
  'updateRawMaterialRequisition' : ActorMethod<
    [OrgId, UpdateRequisitionInput],
    RawMaterialRequisition
  >,
  'updateRefundRequest' : ActorMethod<
    [OrgId, bigint, string],
    [] | [GstRefundRequest]
  >,
  'updateRole' : ActorMethod<[OrgId, UpdateRoleInput], [] | [Role]>,
  'updateRoutingOperation' : ActorMethod<
    [OrgId, UpdateRoutingOperationInput],
    RoutingOperation
  >,
  'updateSalesOrder' : ActorMethod<[OrgId, UpdateSalesOrderInput], SalesOrder>,
  'updateScrapRecord' : ActorMethod<
    [OrgId, UpdateScrapRecordInput],
    ScrapRecord
  >,
  'updateShipment' : ActorMethod<
    [OrgId, bigint, UpdateShipmentInput],
    [] | [Shipment]
  >,
  'updateShipmentStatus' : ActorMethod<
    [OrgId, bigint, ShipmentStatus],
    [] | [Shipment]
  >,
  'updateShopFloorControl' : ActorMethod<
    [OrgId, UpdateShopFloorInput],
    ShopFloorControl
  >,
  'updateWorkOrder' : ActorMethod<[OrgId, UpdateWorkOrderInput], WorkOrder>,
  'upsertStockLevel' : ActorMethod<[OrgId, UpdateStockLevelInput], StockLevel>,
  'voidInvoice' : ActorMethod<[OrgId, InvoiceId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];